GET http://localhost:8080/api/profiles

###
GET http://localhost:8080/api/profiles/610d7963859145681accee13

###
POST http://localhost:8080/api/profiles
content-type: application/json

{
    "name": "Susan",
    "lastname": "Foo",
    "age": "32",
    "email": "susanfoo12@gmail.com"
}

###
DELETE http://localhost:8080/api/profiles/610d975bcbef403df059c675

###
PATCH http://localhost:8080/api/profiles/610ea02d25c4273ee41fd764
Content-Type: application/json

{
    "_id": "610ea02d25c4273ee41fd764",
    "name": "PAPU",
    "lastname": "Lopez Lopez",
    "email" : "hola@gmail.com",
    "age" : "20"
}